In [1]:
import numpy as np

# Define the hidden states and attention vector
hidden_states = np.array([[0.7, 0.2, 0.3, 0.1],
                          [0.2, 0.7, 0.3, 0.1],
                          [0.0, 0.6, 0.4, 0.3],
                          [0.1, 0.1, 0.0, 0.9]])

attention_vector = np.array([0.5, 0.2, 0.4, 0.1])

# Calculate the attention scores
attention_scores = np.dot(hidden_states, attention_vector)

# Print the attention scores
print(attention_scores)


[0.52 0.37 0.31 0.16]


In [2]:
a =  np.array([0.7, 0.2, 0.3, 0.1])
b = np.array([0.5, 0.2, 0.4, 0.1])
np.dot(a,b)

0.52

In [5]:
# Calculate the attention distribution using the softmax function
attention_dist = np.exp(attention_scores) / np.sum(np.exp(attention_scores))

# round the attention distribution to 2 decimal places
attention_dist = np.round(attention_dist, 3)

# Print the attention distribution
print(attention_dist)

[0.297 0.255 0.241 0.207]


In [6]:
# Calculate the attention output
attention_output = np.dot(hidden_states.T, attention_dist)

# Print the attention output
print(attention_output)

[0.2796 0.4032 0.262  0.3138]
